# Generated by Django 4.1.1 on 2022-09-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentportal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinecoursesprofile",
            name="year",
            field=models.IntegerField(default=2022),
        ),
    ]
