# Generated by Django 4.1.1 on 2022-09-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentportal", "0003_auto_20220929_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathonprofile",
            name="title",
            field=models.TextField(default=""),
        ),
    ]
